### ISSUE TITLE
use a button; not a gif...

### ISSUE THREAD

**Issue by proseLA** [lat9/encrypted_master_password#24]
hi cindy,
in keeping with bootstrap, zc v156 and buttons (which i like much more), i think the following line:

https://github.com/lat9/encrypted_master_password/blob/1be900d70ed4501ceb0362c6a8f9c7acd804b386/YOUR_ADMIN/includes/classes/observers/class.emp_admin_customers_observer.php#L60

is better suited with:
`'text' => '<div align="center"><form target="_blank" name="login" action="' . zen_catalog_href_link(FILENAME_LOGIN, '', 'SSL') . '" method="post">' . zen_draw_hidden_field('email_address', $p1->customers_email_address) . '<input class="btn btn-primary" type="submit" value="' . EMP_BUTTON .'"></form></div>'`

in the extra definitions language file, we could then add:

`define('EMP_BUTTON', 'Place Order');`

and then get rid of that gif (button_placeorder.gif); or leave the gif for those who have trouble upgrading.

not really a functional change; but much better looking!

i would do a PR if u want (although i have no fork on this plugin...); else i remain on the outskirts looking in!

best,
p.

**Comment by lat9** [comment]
Agreed, @proseLA.  I've been considering a similar, Zen Cart version-specific, change for [Edit Orders](https://github.com/lat9/edit_orders).

**Comment by lat9** [comment]
@Zen4All, how would I translate _Place Order_ into Dutch?

**Comment by Zen4All** [comment]
Hello Cindy, that is the correct translation.
