### ISSUE TITLE
Allow customization of "type" of on-screen message displayed

### ISSUE THREAD

**Issue by torvista** [lat9/encrypted_master_password#27]
Since the unique identifier for the account is the email address, I swap round the message parameters:

>  ADMIN LOGGED IN using account: steve@emailaddress.com (Stephen BL Switzerland)

I also prefer the message type to be caution rather than success as this type of operation is an anomaly and I think it should stand out as "not quite right" as opposed to "all is ok"!

**Comment by lat9** [comment]
Since the message can be overridden by the current template and that message uses "argument swapping" via sprintf, you can re-arrange those parameters in the message itself.

I'll consider providing a message-severity definition (also in that extra_definitions language-file).

**Comment by lat9** [comment]
You can now edit the EMP storefront's language-specific `extra_definitions` file to modify the message severity.

**Comment by lat9** [comment]
@torvista, since you opened this issue it's yours to close if you feel that it's been corrected.
