### ISSUE TITLE
little bit of an issue with osh code in orders.php

### ISSUE THREAD

**Issue by barco57** [lat9/encrypted_master_password#7]
multi line comment problem
See attached image
![encrypted_master_password_issue](https://cloud.githubusercontent.com/assets/1237035/7851145/ddc8cf5c-04b0-11e5-8254-0de1d054de6a.png)

**Comment by lat9** [comment]
Thanks for the report, barco57; I'll give that a look later today.

**Comment by lat9** [comment]
Corrected in v2.0.2.  Also propagated the change to all other plugins that are using the osh_updated_by plugin.
